return {
  "mfussenegger/nvim-dap",
  config = Config("dap", function(dap)
    kset("n", "<F5>", dap.continue)
    kset("n", "<F10>", dap.step_over)
    kset("n", "<F11>", dap.step_into)
    kset("n", "<F12>", dap.step_out)
    kset("n", "<Leader>b", dap.toggle_breakpoint)
    kset("n", "<Leader>B", dap.set_breakpoint)
    kset("n", "<Leader>lp", function()
      dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
    end)
    kset("n", "<Leader>dr", dap.repl.open)
    kset("n", "<Leader>dl", dap.run_last)
    kset({ "n", "v" }, "<Leader>dh", function()
      require("dap.ui.widgets").hover()
    end)
    kset({ "n", "v" }, "<Leader>dp", function()
      require("dap.ui.widgets").preview()
    end)
    kset("n", "<Leader>df", function()
      local widgets = require("dap.ui.widgets")
      widgets.centered_float(widgets.frames)
    end)
    kset("n", "<Leader>ds", function()
      local widgets = require("dap.ui.widgets")
      widgets.centered_float(widgets.scopes)
    end)
  end),
}
